--- 
install: 
  - "npm install -g firebase-tools"
language: node_js
node_js: 
  - "11.13.0"
script: 
  - "npm install"
  - "npm run build"
  - "firebase deploy --only hosting --token $FIREBASE_TOKEN"